from enum import Enum

class UgvState(Enum):
    BOOT = 0
    WAIT_FOR_RADIO_LINK = 1
    PREFLIGHT_CHECKS = 2
    WAIT_FOR_DESTINATION = 3
    ACK_DESTINATION = 4
    START_MOTION = 5
    NAVIGATE_TO_DESTINATION = 6
    AVOID_OBSTACLE = 7
    EXPECT_UAV_TOUCHDOWN = 8
    TOUCHDOWN_CONFIRMED = 9
    CONTINUE_TO_DESTINATION = 10
    STOP_AT_DESTINATION = 11
    MISSION_COMPLETE = 12
    
    # Failsafes
    COMM_LOSS = 90
    DESTINATION_TIMEOUT = 91
    ESTOP = 92
    DRIVE_FAULT = 93
