from enum import Enum

class UavState(Enum):
    BOOT = 0
    WAIT_FOR_AUTOPILOT = 1
    WAIT_FOR_RADIO_LINK = 2
    PREFLIGHT_CHECKS = 3
    ARM = 4
    TAKEOFF = 5
    SEARCH_DESTINATION_MARKER = 6
    ESTIMATE_DESTINATION = 7
    SEND_DESTINATION_TO_UGV = 8
    WAIT_FOR_UGV_ACK = 9
    SEARCH_UGV_LANDING_MARKER = 10
    TRACK_MOVING_UGV = 11
    PRECISION_LANDING_APPROACH = 12
    TOUCHDOWN_CONFIRM = 13
    RIDE_ALONG_TIMER = 14
    MISSION_COMPLETE = 15
    
    # Failsafes
    COMM_LOSS = 90
    TARGET_LOSS = 91
    RANGEFINDER_BAD = 92
    CAMERA_BAD = 93
    EKF_BAD = 94
    ABORT_LAND = 95
    EMERGENCY_LAND = 96
